# Generated by Django 5.1.6 on 2025-03-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='nome')),
                ('telefone', models.TextField(db_column='telefone')),
                ('data_cadastro', models.DateField(db_column='data_cadastro')),
            ],
            options={
                'db_table': 'tb_cliente',
                'unique_together': {('nome', 'telefone')},
            },
        ),
    ]
