# Generated by Django 5.1.6 on 2025-03-04 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtechwebs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTipoProduto',
            fields=[
                ('cod', models.AutoField(db_column='cod', primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_column='descricao', null=True, unique=True)),
                ('margem', models.FloatField(blank=True, db_column='margem', null=True)),
            ],
            options={
                'db_table': 'tb_tipo_produto',
            },
        ),
        migrations.CreateModel(
            name='TbFornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(db_column='id_fornecedor', primary_key=True, serialize=False)),
                ('nome_empresa', models.TextField(db_column='nome_empresa')),
                ('tipo_empresa', models.TextField(blank=True, db_column='tipo_empresa', null=True)),
                ('data_cadastro', models.DateField(db_column='data_cadastro')),
            ],
            options={
                'db_table': 'tb_fornecedor',
                'unique_together': {('nome_empresa', 'tipo_empresa')},
            },
        ),
        migrations.CreateModel(
            name='TbProduto',
            fields=[
                ('id_produto', models.AutoField(db_column='id_produto', primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='nome')),
                ('preco_custo', models.FloatField(db_column='preco_custo')),
                ('fabricante', models.TextField(blank=True, db_column='fabricante', null=True)),
                ('marca', models.TextField(blank=True, db_column='marca', null=True)),
                ('cor', models.TextField(blank=True, db_column='cor', null=True)),
                ('data_cadastro', models.DateField(db_column='data_cadastro')),
                ('estoque', models.IntegerField(db_column='estoque')),
                ('imagem', models.CharField(blank=True, db_column='imagem', max_length=300, null=True)),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.DO_NOTHING, to='gtechwebs.tbfornecedor')),
                ('tipo_produto', models.ForeignKey(db_column='cod', on_delete=django.db.models.deletion.DO_NOTHING, to='gtechwebs.tbtipoproduto')),
            ],
            options={
                'db_table': 'tb_produto',
                'unique_together': {('nome', 'id_fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='TbVenda',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='data')),
                ('quantidade', models.IntegerField(blank=True, db_column='quantidade', null=True)),
                ('preco_venda', models.FloatField(db_column='preco_venda')),
                ('lucro', models.FloatField(blank=True, db_column='lucro', null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gtechwebs.tbcliente')),
                ('id_produto', models.ForeignKey(blank=True, db_column='Id_produto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gtechwebs.tbproduto')),
            ],
            options={
                'db_table': 'tb_venda',
            },
        ),
    ]
