# Generated by Django 5.1.6 on 2025-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtechwebs', '0002_tbtipoproduto_tbfornecedor_tbproduto_tbvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcliente',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, db_column='data_cadastro'),
        ),
    ]
