# Generated by Django 5.1.6 on 2025-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtechwebs', '0003_alter_tbcliente_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbfornecedor',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, db_column='data_cadastro'),
        ),
        migrations.AlterField(
            model_name='tbproduto',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, db_column='data_cadastro'),
        ),
        migrations.AlterField(
            model_name='tbproduto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
