# Generated by Django 5.1.6 on 2025-03-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtechwebs', '0004_alter_tbfornecedor_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcliente',
            name='email',
            field=models.TextField(blank=True, db_column='email', null=True),
        ),
    ]
