# Generated by Django 5.1.6 on 2025-03-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtechwebs', '0005_tbcliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbvenda',
            name='id_produto',
            field=models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gtechwebs.tbproduto'),
        ),
    ]
